# Site settings
title: Alvin Lee
description: 'University of Waterloo Computer Science | Game Designer'
url: 'http://alvin-lee.me'
#url: 'localhost:4000'
baseurl: '/'
google_analytics: 'UA-106754428-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alvin Lee'
  email: leealvin71@gmail.com
  #twitter_username: _alvinlee_
  #facebook_username: 
  #github_username:  a79lee
  linkedin_username:  a79lee

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
